Update github workflows (#1178)
CLI still doesn't recognise [gel] inside gel.toml. So I updated our
`gel.toml` files inside test folders to use `egdedb`.

Do we want to run some CI tests on Windows machines? All tests we have
run on ubuntu.

At the end I reverted tests to use `edgedb` for the CLI (`edgedb
migrate` etc...) in order to use the current `setup-edgedb` action.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -18,24 +18,24 @@ jobs:
       matrix:
         node-version: ["18", "20", "22"]
         os: [ubuntu-latest]
-        edgedb-version: ["stable"]
+        gel-version: ["stable"]
         include:
           - os: ubuntu-latest
             node-version: "20"
-            edgedb-version: "nightly"
+            gel-version: "nightly"
           - os: ubuntu-latest
             node-version: "20"
-            edgedb-version: "5"
+            gel-version: "5"
           - os: ubuntu-latest
             node-version: "20"
-            edgedb-version: "4"
+            gel-version: "4"
           # - os: ubuntu-latest
           #   node-version: "20"
-          #   edgedb-version: "3"
+          #   gel-version: "3"
           # XXX: macOS is currently unsupported by setup-edgedb
           # - os: macos-latest
           #   node-version: "20"
-          #   edgedb-version: "stable"
+          #   gel-version: "stable"
 
     steps:
       - uses: actions/checkout@v4
@@ -77,16 +77,16 @@ jobs:
         run: |
           yarn format
 
-      - name: Install EdgeDB
+      - name: Install Gel
         uses: edgedb/setup-edgedb@6763b6de72782d9c2e5ecc1095986a1c707da68f
         with:
           instance-name: test
-          server-version: ${{ matrix.edgedb-version }}
-          cli-version: ${{ matrix.edgedb-version == 'nightly' && 'nightly' || 'stable' }}
+          server-version: ${{ matrix.gel-version }}
+          cli-version: ${{ matrix.gel-version == 'nightly' && 'nightly' || 'stable' }}
 
-      - name: Show actual EdgeDB server version
+      - name: Show actual Gel server version
         run: |
-          echo ACTIVE_EDGEDB_VERSION=$(edgedb query 'select sys::get_version_as_str()' -I test) >> $GITHUB_ENV
+          echo ACTIVE_GEL_VERSION=$(gel query 'select sys::get_version_as_str()' -I test) >> $GITHUB_ENV
 
       - name: Install postgis extension
         if: ${{ matrix.edgedb-version == 'nightly' }}
@@ -98,20 +98,20 @@ jobs:
           yarn ci:test
 
       - name: Run query builder integration tests lts
-        if: ${{ matrix.edgedb-version == '3' || matrix.edgedb-version == '4' || matrix.edgedb-version == 'stable' || matrix.edgedb-version == 'nightly' }}
+        if: ${{ matrix.gel-version == '3' || matrix.gel-version == '4' || matrix.gel-version == 'stable' || matrix.gel-version == 'nightly' }}
         run: |
-          turbo run ci:integration-test --filter=@edgedb/integration-lts
-          turbo run bench:types --filter=@edgedb/integration-lts || echo "Benchmark types script failed, proceeding anyway."
+          turbo run ci:integration-test --filter=@gel/integration-lts
+          turbo run bench:types --filter=@gel/integration-lts || echo "Benchmark types script failed, proceeding anyway."
 
       - name: Run query builder integration tests stable
-        if: ${{ matrix.edgedb-version == 'stable' || matrix.edgedb-version == 'nightly' }}
+        if: ${{ matrix.gel-version == 'stable' || matrix.gel-version == 'nightly' }}
         run: |
-          turbo run ci:integration-test --filter=@edgedb/integration-stable
+          turbo run ci:integration-test --filter=@gel/integration-stable
 
       - name: Run query builder integration tests nightly
-        if: ${{ matrix.edgedb-version == 'nightly' }}
+        if: ${{ matrix.gel-version == 'nightly' }}
         run: |
-          turbo run ci:integration-test --filter=@edgedb/integration-nightly
+          turbo run ci:integration-test --filter=@gel/integration-nightly
 
       - name: Typecheck other packages
         run: |
@@ -150,8 +150,8 @@ jobs:
 
       - name: Build and pack CLI wrapper
         run: |
-          yarn workspace edgedb run build
-          yarn workspace edgedb pack --filename=${{ github.workspace }}/edgedb-cli.tar.gz
+          yarn workspace gel run build
+          yarn workspace gel pack --filename=${{ github.workspace }}/edgedb-cli.tar.gz
 
       - name: Test CLI wrapper with npm
         run: |
@@ -159,9 +159,9 @@ jobs:
           cd ${{ runner.temp }}/temp-npm
           npm init -y
           npm install ${{ github.workspace }}/edgedb-cli.tar.gz
-          npm exec edgedb -- project init --non-interactive
-          npm exec edgedb -- --version
-          npm exec edgedb -- query 'select sys::get_version_as_str()'
+          npm exec gel -- project init --non-interactive
+          npm exec gel -- --version
+          npm exec gel -- query 'select sys::get_version_as_str()'
 
       - name: Test CLI wrapper with yarn
         run: |
@@ -169,9 +169,9 @@ jobs:
           cd ${{ runner.temp }}/temp-yarn
           yarn init -y
           yarn add ${{ github.workspace}}/edgedb-cli.tar.gz
-          yarn edgedb project init --non-interactive
-          yarn edgedb --version
-          yarn edgedb query 'select sys::get_version_as_str()'
+          yarn gel project init --non-interactive
+          yarn gel --version
+          yarn gel query 'select sys::get_version_as_str()'
 
       - uses: threeal/setup-yarn-action@ec8c075e62bc497968de40011c2b766f5e8f1ac5
         with:
@@ -185,9 +185,9 @@ jobs:
           yarn init -y
           touch yarn.lock
           yarn add ${{ github.workspace }}/edgedb-cli.tar.gz
-          yarn edgedb project init --non-interactive
-          yarn edgedb --version
-          yarn edgedb query 'select sys::get_version_as_str()'
+          yarn gel project init --non-interactive
+          yarn gel --version
+          yarn gel query 'select sys::get_version_as_str()'
 
       - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
         with:
@@ -199,9 +199,9 @@ jobs:
           cd ${{ runner.temp}}/temp-pnpm
           pnpm init
           pnpm add ${{ github.workspace }}/edgedb-cli.tar.gz
-          pnpm exec edgedb project init --non-interactive
-          pnpm exec edgedb --version
-          pnpm exec edgedb query 'select sys::get_version_as_str()'
+          pnpm exec gel project init --non-interactive
+          pnpm exec gel --version
+          pnpm exec gel query 'select sys::get_version_as_str()'
 
       - uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135
       - name: Test CLI wrapper with bun
@@ -210,6 +210,6 @@ jobs:
           cd temp-bun
           bun init
           bun add ${{ github.workspace }}/edgedb-cli.tar.gz
-          bun edgedb project init --non-interactive
-          bun edgedb --version
-          bun edgedb query 'select sys::get_version_as_str()'
+          bun gel project init --non-interactive
+          bun gel --version
+          bun gel query 'select sys::get_version_as_str()'
